plugins:
  algolia_enabled:
    default: false
    client: false
  algolia_application_id:
    default: ''
    client: true
  algolia_search_api_key:
    default: ''
    client: true
  algolia_admin_api_key:
    default: ''
    client: false
  algolia_discourse_username:
    default: 'system'
    client: false
